---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    intuit_alert: "true"
    iks.intuit.com/managed: "false"
  name: label-test-ns
---
apiVersion: v1
kind: Service
metadata:
  name: label-test-express
  namespace: label-test-ns
  labels:
    intuit_alert: "true"
    iks-metric: http-metrics
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: iks-metric
      protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: label-test-express
---
apiVersion: v1
kind: Service
metadata:
  name: label-test-nonexpress
  namespace: label-test-ns
  labels:
    intuit_alert: "true"
    iks-metric: http-metrics
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: iks-metric
      protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: label-test-nonexpress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: label-test-express
  namespace: label-test-ns
  labels:
    intuit_alert: "true"
    app: label-test-express
    assetAlias: Intuit.platformrun.compute.label.test
    assetId: '5840060409812502485'
    env: qal
    l1: platformrun
    l2: compute
    policyId: p-bjgvnysj7smh
    region: usw2
    role: stable
    workspace: label-test220628-qal
spec:
  selector:
    matchLabels:
      app: label-test-express
  template:
    metadata:
      labels:
        intuit_alert: "true"
        app: label-test-express
        assetAlias: Intuit.platformrun.compute.label.test
        assetId: '5840060409812502485'
        env: qal
        l1: platformrun
        l2: compute
        policyId: p-bjgvnysj7smh
        region: usw2
        role: stable
        workspace: label-test220628-qal
    spec:
      containers:
        - name: app
          resources:
            requests:
              cpu: "250m"
              memory: "1G"
            limits:
              cpu: "500m"
              memory: "2G"
          image: docker.intuit.com/personal/aauddy/spring-boot-metrics-demo:v2
          imagePullPolicy: Always
          ports:
            - name: app
              containerPort: 8080
              protocol: TCP
            - name: metrics
              containerPort: 8081
              protocol: TCP
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: label-test-nonexpress
  namespace: label-test-ns
  labels:
    intuit_alert: "true"
    app: label-test-nonexpress
    role: stable
spec:
  selector:
    matchLabels:
      app: label-test-nonexpress
  template:
    metadata:
      labels:
        intuit_alert: "true"
        app: label-test-nonexpress
        role: stable
    spec:
      containers:
        - name: app
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "500m"
          image: docker.intuit.com/personal/aauddy/spring-boot-metrics-demo:v2
          imagePullPolicy: Always
          ports:
            - name: app
              containerPort: 8080
              protocol: TCP
            - name: metrics
              containerPort: 8081
              protocol: TCP
      restartPolicy: Always
